"""Criar tabelas de jogadores e duplas

Revision ID: a8b768413c54
Revises: 
Create Date: 2024-09-10 14:43:45.259481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8b768413c54'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dupla',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('partidas_vencidas', sa.Integer(), nullable=True),
    sa.Column('partidas_perdidas', sa.Integer(), nullable=True),
    sa.Column('saldo', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jogador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('partidas_vencidas', sa.Integer(), nullable=True),
    sa.Column('partidas_perdidas', sa.Integer(), nullable=True),
    sa.Column('saldo', sa.Integer(), nullable=True),
    sa.Column('dupla_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dupla_id'], ['dupla.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jogador')
    op.drop_table('dupla')
    # ### end Alembic commands ###
